export const config = {
  DEFAULT_LOCALE: "en-US",
  DEFAULT_BASE_CURRENCY: "USD",
  DEFAULT_ASSETS: ["BTC", "ETH"],
  DEFAULT_SPLIT_PERCENT: 70,
  DEFAULT_AMOUNT: 10000,
  REFRESH_INTERVAL_MS: 60_000,
};
