export const config = {
  COINBASE_EXCHANGE_RATES_URL: "https://api.coinbase.com/v2/exchange-rates",
  DEFAULT_LOCALE: "en-US",
  DEFAULT_BASE_CURRENCY: "USD",
  DEFAULT_ASSETS: ["BTC", "ETH"],
  DEFAULT_SPLIT_PERCENT: 70,
  DEFAULT_AMOUNT: 10000,
  REFRESH_INTERVAL_MS: 60_000,
};
